# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('accession_number', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='numer_dostepu')),
                ('name', models.CharField(max_length=20, verbose_name='nazwa')),
                ('start_pos', models.IntegerField()),
                ('end_pos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ligand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='nazwa')),
                ('description', models.TextField(verbose_name='opis')),
            ],
        ),
        migrations.CreateModel(
            name='Ligand_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='nazwa')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('accession_number', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='numer_dostepu')),
                ('taxid', models.IntegerField()),
                ('common_name', models.CharField(max_length=30, verbose_name='nazwa_zwyczajowa')),
                ('scientific_name', models.CharField(max_length=30, verbose_name='nazwa_naukowa')),
            ],
        ),
        migrations.CreateModel(
            name='Promoter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='nazwa')),
                ('sequence', models.TextField(verbose_name='sekwencja')),
                ('start_pos', models.IntegerField()),
                ('end_pos', models.IntegerField()),
                ('genes_under_operon_regulation', models.CharField(max_length=30, verbose_name='geny_pod_regulacja_operonu')),
                ('_3D_structure', models.TextField(verbose_name='struktura 3D')),
                ('effect', models.IntegerField(choices=[(1, 'ACTIVATION'), (0, 'UNKNOWN'), (-1, 'SILECING')])),
                ('mechanism', models.CharField(choices=[('TRN', 'TRANSCRIPTION'), ('TRL', 'TRANSLATION'), ('UN', 'UNKNOWN'), ('DG', 'DEGRADATION')], max_length=3)),
                ('strand', models.CharField(choices=[('+', 'LEADING STRAND'), ('-', 'LAGGING STRAND')], max_length=1)),
                ('article', models.ManyToManyField(to='database.Article')),
            ],
        ),
        migrations.CreateModel(
            name='RiboClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='nazwa')),
                ('description', models.TextField(verbose_name='opis')),
                ('alignment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RiboFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='nazwa')),
                ('description', models.TextField(verbose_name='opis')),
                ('alignment', models.TextField()),
                ('ribo_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.RiboClass')),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('without_ligand', models.TextField(verbose_name='bez_ligandu')),
                ('with_ligand', models.TextField(verbose_name='z_ligandem')),
                ('predicted', models.TextField(verbose_name='przewidziana')),
            ],
        ),
        migrations.CreateModel(
            name='Terminator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.RiboFamily'),
        ),
        migrations.AddField(
            model_name='record',
            name='gene',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.Gene'),
        ),
        migrations.AddField(
            model_name='record',
            name='ligand',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.Ligand'),
        ),
        migrations.AddField(
            model_name='record',
            name='organism',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Organism'),
        ),
        migrations.AddField(
            model_name='record',
            name='promoter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.Promoter'),
        ),
        migrations.AddField(
            model_name='record',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Structure'),
        ),
        migrations.AddField(
            model_name='record',
            name='terminator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.Terminator'),
        ),
        migrations.AddField(
            model_name='ligand',
            name='ligand_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Ligand_class'),
        ),
        migrations.AddField(
            model_name='gene',
            name='organism',
            field=models.ManyToManyField(to='database.Organism'),
        ),
    ]
