# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riboclass',
            name='ribo_family',
        ),
        migrations.AddField(
            model_name='ribofamily',
            name='ribo_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.RiboClass'),
        ),
    ]
